packaging_format = 2

id = "yakforms"
name = "Yakforms"
description.en = "Create online webforms and surveys"
description.fr = "Créez des formulaires et questionnaires en ligne"

version = "1.1~ynh1"

maintainers = [""]

[upstream]
license = "GPL-2.0-only"
website = "https://yakforms.org"
admindoc = "https://docs.yakforms.org/"
code = "https://framagit.org/yakforms/yakforms"


[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/poll"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://packages.yakforms.org/yakforms_distribution_1.1.zip"
        sha256 = "96c026e914b29ea81c8e86aeca2754af51314ca0529cf7d3005f75653827520b"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql php8.2-fpm php8.2-cli php8.2-gd php8.2-xml php8.2-ldap php8.2-mbstring php8.2-pgsql"

    [resources.database]
    type = "postgresql"
